# Generated by Django 4.1.2 on 2022-10-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo_Tematico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PLano_Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('objetivo_geral', models.CharField(max_length=250)),
                ('ementa', models.CharField(max_length=500)),
                ('carga_horaria', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('avaliacao', models.FloatField()),
                ('eixo_tematico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eixo_tematico')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('titulacao', models.CharField(max_length=120)),
                ('senha', models.CharField(max_length=250)),
                ('termo_uso', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Topico_Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=500)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plano_curso')),
            ],
        ),
        migrations.AddField(
            model_name='plano_curso',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('assinado', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plano_curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
            ],
        ),
    ]
